remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Securitah!
description: Blogging about Cyber Security since at least 5000 BC
